### ISSUE TITLE
No process works with last genModelAddon version 2.3.0

### ISSUE THREAD

**Issue by ChatNoir76** [opcoach/genModelAddon#87]
Bonjour Olivier,

Je viens de reprendre un de mes projets afin de refondre le model eCore.

Je viens de réinstaller Eclipse 12-2020 ainsi que genModelAddon 2.3.0

Lors de la génération de la structure, rien ne se passe.

mon projet en question : 
[mon Projet](https://github.com/ChatNoir76/Enigmator/tree/feature/model)

Merci pour ton aide,

Julien R
(formation RCP3 et git)

**Comment by opcoach** [comment]
Salut Julien,

J'ai remonté ton projet, dans mon Eclipse 2021-09, avec le dernier genModelAddon, et tout fonctionne bien pour moi... quand tu dis rien n'est généré ... pourtant tu as eu du code généré dans ton repository git puisque je l'ai récupéré... 

C'est quoi qui ne fonctionne pas exactement ? 

Attention, le GenerateDeveloper Structure, ne génère le code dans src qu'une seule fois et il faut le relancer si tu recréés des nouvelles EClass dans ton ecore. 

Pour ma part, j'utilise GMA tous les jours sur un développement perso et j'ai aucun soucis de génération. 

Je te joins un screenshot de ce que j'ai... dis moi ce que tu penses qu'il manque... 

PS : sinon ajoute une ligne 'target/' dans ton .gitignore racine pour ne pas livrer les répertoire target... ;)
![EnigmatorGMA](https://user-images.githubusercontent.com/1716878/140285318-a0747126-cce0-436e-9a94-ca11c82dc085.jpg)

**Comment by ChatNoir76** [comment]
Bonjour Olivier, 

Alors justement, c'est sur la branche feature/model que ça ne fonctionne pas.

La branche Main et develop contiennent un model exemple. c'était une solution temporaire.

Le nouveau "vrai" model est donc sur la feature, j'ai supprimé le contenu src et src-gen mais la génération ne fonctionne plus.

Je vais voir pour te faire une copie écran de mon problème dès ce soir.

Merci pour ton retour,

Julien

**Comment by ChatNoir76** [comment]
Screenshot avant la génération (src et src-gen) sont vides [branche feature/model]
![image](https://user-images.githubusercontent.com/39826701/140546444-0578b507-f836-4a56-8742-12ac292a81ef.png)

Puis une fois la génération effectuée, il ne se passe rien, il n'y a rien dans src et src-gen.

**Comment by opcoach** [comment]
Ok, dans le .log de ton workspace tu as la raison que je recolle ci dessous... 

Je ne sais pas pourquoi cela a produit cette erreur, mais maintenant ca génère bien si tu vas dans les properties de ton projet -> Java Build Path, onglet 'source' et tu supprimes les deux répertoires que tu as actuellement, puis tu génères... 

En fait l'un de tes répertoires source indiqué contenait un / à la fin (src/).  Je joins la copie d'écran ...

Il faudrait que je contrôle qu'il peut y avoir un soucis lorsque un des répertoires source se finit par un '/'.

je laisse donc ce but ouvert... 



!ENTRY org.eclipse.e4.ui.workbench 4 0 2021-11-05 18:57:55.105
!MESSAGE Command 'com.opcoach.genmodeladdon.generateSourceFolderE4' failed
!STACK 0
org.eclipse.core.commands.ExecutionException: Error executing 'com.opcoach.genmodeladdon.generateSourceFolderE4': Java Model Exception: Java Model Status [Build path contains duplicate entry: 'src' for project 'fr.chatnoir.enigmator.model']
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:170)
        at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
        at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
        at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
        at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
        at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4524)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1522)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1545)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1530)
        at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4310)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3883)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1041)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
        at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
Caused by: org.eclipse.e4.core.di.InjectionException: Java Model Exception: Java Model Status [Build path contains duplicate entry: 'src' for project 'fr.chatnoir.enigmator.model']
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:68)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:323)
        at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
        at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
        at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
        ... 35 more
Caused by: Java Model Exception: Java Model Status [Build path contains duplicate entry: 'src' for project 'fr.chatnoir.enigmator.model']
        at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:802)
        at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3656)
        at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3616)
        at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3672)
        at com.opcoach.genmodeladdon.core.GenerateDevStructure.setFolderAsSourceFolder(GenerateDevStructure.java:230)
        at com.opcoach.genmodeladdon.core.GenerateDevStructure.generateDevStructure(GenerateDevStructure.java:141)
        at com.opcoach.genmodeladdon.core.GenerateDevStructure.generateDevStructure(GenerateDevStructure.java:130)
        at com.opcoach.genmodeladdon.handlers.GeneratedDerivedSourceFolder.execute(GeneratedDerivedSourceFolder.java:63)
        at com.opcoach.genmodeladdon.handlers.GenerateParentHandler.execute(GenerateParentHandler.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
        ... 40 more
$  
![issue87](https://user-images.githubusercontent.com/1716878/140557762-f363c19b-0c9d-4c5d-b582-ba00d2bc50da.jpg)

**Comment by opcoach** [comment]
Une remarque aussi, gère tes fichiers .project dans ton git également ainsi que tous les settings...

**Comment by ChatNoir76** [comment]
Effectivement, une fois supprimé, la génération a fonctionné.
Grand merci pour ce débug.

Concernant ta remarque, pour gérer les .project dans git, ainsi que tous les settings... que dois je faire?
car les .project par exemple sont push car non présent dans le git ignore, donc ils sont gérés non?

**Comment by opcoach** [comment]
Cool :) 

Il semble que certains .project n’étaient pas présents dans le git que j’ai récupéré car dans la vue git staging je les voyais créés…

Il suffira de faire un commit qui les contient…  

L’idée est de pouvoir réimporter tous les projets avec leur config (et notamment les filtres d’affichage qui sont stockés dans les .project), à partir d’un repo git cloné dans un workspace vierge eclipse. 

N’hésite pas si tu as d’autres questions…

Amuse toi bien :) 

A+
Olivier



  <http://www.opcoach.com/>
Olivier Prouvost

Formation et Expertise Eclipse

 	
 ***@***.***
 http://www.opcoach.com <http://www.opcoach.com/>
 +33(0)6 28 07 65 64
 OPCoach_Eclipse <https://twitter.com/OPCoach_Eclipse>
 Profil linkedin
 <https://fr.linkedin.com/in/olivierprouvost>	 	  <https://eclipse.org/membership/showMember.php?member_id=987>
